version: '3.8'

services:
  pokemon-ai:
    build: .
    container_name: pokemon-ai
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_TOKEN=MTMyMzQ2MjkyMzM1NTY4NDkzNA.GkWJIw.sQwgS2mC-pigD2V1__HDBS7opa38A5S3qMlPOI
      - GOOGLE_API_KEY=AIzaSyDlb8JtTZYOxua-SvXNvMAAbioJ4OVtGSw
    command: python pokemon-AI.py